== Important documents in this repo

* link:src/main/asciidoc/protocols[Meeting Protocols]
* link:src/main/asciidoc/time_recording.adoc[Time recording (Zeiterfassung)]
* link:src/main/asciidoc/pflichtenheft.adoc[Requirements specification (Pflichtenheft)]
* link:src/main/asciidoc/developer_documentation.adoc[Developer documentation (Entwicklerdokumentation)]

== The repository layout

The repository follows the standard Maven project layout. Nearly all artifacts are stored in a subdirectory of `src/`:

  src/
  ├── main/
  │   ├── asciidoc/   -- Documentation of the development process and application (Asciidoc format)
  │   ├── java/       -- Main source code of the application, separated into packages
  │   └── resources/  -- Static assets (images, stylesheets), Thymeleaf templates, etc.
  └── test/
      └── java/       -- Source code of JUnit tests is stored separately

**Pro tip:** In GitHub, press *t* and a "fuzzy file finder" will appear, making it easy to navigate to a file.

== How to run the application?

* In the IDE: find `Application.java`, right-click project, select "Run As > Java Application"
* From the command line: run `./mvnw spring-boot:run`

== How to package the application?

* Run `./mvnw clean package`. The packaged application (a JAR in `target/`) can be run with `java -jar $jarName`.
